apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "standard-service.fullname" . }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "standard-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "standard-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "standard-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.serviceAccount }}
      serviceAccount: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      # serviceAccountName: {{ include "standard-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ required "Image must be specified" .Values.image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            {{- if .Values.service.ports.http }}
            - name: https
              containerPort: {{ .Values.service.ports.http }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.health }}
            - name: http-health
              containerPort: {{ .Values.service.ports.health }}
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.metrics }}
            - name: http-metrics
              containerPort: {{ .Values.service.ports.metrics }}
              protocol: TCP
            {{- end }}
          # livenessProbe:
          #   timeoutSeconds: {{ .Values.healthCheckTimeoutSeconds }}
          #   httpGet:
          #     path: /health
          #     port: http-health
          # readinessProbe:
          #   timeoutSeconds: {{ .Values.healthCheckTimeoutSeconds }}
          #   httpGet:
          #     path: /health
          #     port: http-health
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.envVars | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
