{{- $fullName := include "standard-service.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ $fullName }}
  labels:
    {{- include "standard-service.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.useDefaultBackend }}
  defaultBackend:
    service:
      name: {{ $fullName }}
      port:
        number: 80
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ default 80 .port.number }}
          {{- end }}
    {{- end }}
  # {{- else }}
  #   - host: {{ $fullName }}.internal.{{- include "ingressHostname" . }}
  #     http:
  #       paths:
  #         {{- if .Values.service.ports.http }}
  #         - path: /
  #           pathType: Prefix
  #           backend:
  #             service:
  #               name: {{ $fullName }}
  #               port:
  #                 name: http
  #         {{- end }}
  #         - path: /health
  #           pathType: Prefix
  #           backend:
  #             service:
  #               name: {{ $fullName }}
  #               port:
  #                 name: http-health
  #         - path: /metrics
  #           pathType: Prefix
  #           backend:
  #             service:
  #               name: {{ $fullName }}
  #               port:
  #                 name: http-metrics
  # {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- else }}
  tls:
    - hosts:
      - {{ $fullName }}.{{- include "ingressHostname" . }}
      secretName: {{ include "tlsCertName" . }}
  {{- end }}
