{{- if .Values.sealedSecrets.enabled }}
{{- range .Values.sealedSecrets.values }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    type: Opaque
    metadata:
      name: {{ .name }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  encryptedData:
    {{- toYaml .encryptedData | nindent 4 }}
{{- end }}
{{- end }}
