{{- if .Values.sealedSecrets.enabled }}
{{- range .Values.sealedSecrets.values }}
___
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    creationTimestamp: null
    name: {{ .name }}
    annotations:
        {{- default dict .annotations | toYaml | nindent 4 }}
spec:
    template:
        type: Opaque
        metadata:
            creationTimestamp: null
            name: {{ .name }}
            annotations:
                {{- default dict .annotations | toYaml | nindent 8 }}
    encryptedData:
        {{- toYaml .encryptedData | nindent 4 }}
{{- end }}
{{- end }}
